require 'tmpdir'

# TODO:
# make sure we're on master and git cache isn't dirty

task :release do
  Dir.mktmpdir do |dir|
    temp_location = "#{dir}/setup"
    FileUtils.copy_file('setup.sh', temp_location)
    `git checkout gh-pages`
    FileUtils.copy_file(temp_location, 'setup')
    `git add setup`
    `git commit -m "release #{Time.now}"`
    `git checkout -`
  end
end

HEADER = <<EOF
#!/bin/bash

############
# WARNING: This file is generated by a rake task. Do not edit it directly.
############
EOF

def read_segment(filename)
  segment = File.read('setup/' + filename)
  segment.sub(%r|^#!/bin/bash|, '')
end

def append_segment(targetfile, filename)
  targetfile.write("#######\n# #{filename}")
  targetfile.write( read_segment(filename) )
  targetfile.write("\n\n")
end

task :build do
  File.open('setup.sh', 'w') do |setup|
    setup.write(HEADER)
    setup.write( read_segment('functions.sh') )
    parts = Dir.new('setup').sort
    parts.each do |part|
      next unless part.match(/^\d\d_.*\.sh$/)
      append_segment(setup, part)
    end
  end
end
